/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/auth/admin/remove-member': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Deletes a company member (admin only).
		 * @description # Errors
		 *     Returns an error if the user is not an admin or if the deletion fails.
		 */
		delete: operations['admin_delete_member'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/admin/update-member': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Updates a company member's profile (admin only).
		 * @description # Errors
		 *     Returns an error if the user is not an admin, the request is invalid, or the update fails.
		 */
		put: operations['admin_update_member_profile'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/company/branches': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Lists all branches for the user's company. */
		get: operations['list_branches'];
		/** Updates an existing branch for the user's company. */
		put: operations['update_branch'];
		/** Creates a new branch for the user's company. */
		post: operations['create_branch'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/company/members': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieves all members belonging to the current user's company.
		 * @description # Errors
		 *     Returns an error if the user is not associated with a company or if the database query fails.
		 */
		get: operations['get_company_members'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/google/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Handles the callback from Google after the user has authorized the application.
		 * @description # Errors
		 *     Returns an error if the state is invalid, code exchange fails, or user creation fails.
		 */
		get: operations['google_callback'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/google/initiate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Initiates the Google OAuth login flow by redirecting the user to Google.
		 * @description # Errors
		 *     Returns an error if OAuth is not configured or if URL generation fails.
		 */
		get: operations['initiate_google_login'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/google/link': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Directly links a Google account to an existing user profile using a callback code.
		 * @description # Errors
		 *     Returns an error if the state is invalid, code exchange fails, or linking fails.
		 */
		post: operations['link_google_account'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/google/link/confirm': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Confirms linking a Google account to an existing user profile.
		 * @description # Errors
		 *     Returns an error if the link token is invalid/expired or if the linking operation fails.
		 */
		post: operations['confirm_google_link'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/google/unlink': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Unlinks a Google account from the user profile.
		 * @description # Errors
		 *     Returns an error if the user has no password set (cannot unlink last auth method) or if unlinking fails.
		 */
		delete: operations['unlink_google_account'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/accept': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Accepts an invitation and creates a new user account.
		 * @description # Errors
		 *     Returns an error if the token is invalid/expired, validation fails, or account creation fails.
		 */
		post: operations['accept_invitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Cancels a pending invitation.
		 * @description # Errors
		 *     Returns an error if the user is not authorized or if the cancellation fails.
		 */
		put: operations['cancel_invitation'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/details': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieves details of an invitation using its token.
		 * @description # Errors
		 *     Returns an error if the invitation is not found or if there's a database error.
		 */
		get: operations['get_invitation_details'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/pending': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieves all pending invitations for the current user's company.
		 * @description # Errors
		 *     Returns an error if the user is not authorized or if the query fails.
		 */
		get: operations['get_pending_invitations'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/send': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sends an invitation to a new user.
		 * @description # Errors
		 *     Returns an error if the user is not authorized, the email is invalid, or the invitation fails to send.
		 */
		post: operations['invite_user'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticates a user and returns a JWT token.
		 * @description # Errors
		 *     Returns an error if credentials are invalid or if authentication fails.
		 */
		post: operations['login'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieves the profile information of the currently authenticated user.
		 * @description # Errors
		 *     Returns an error if the user is not found or if there's a database error.
		 */
		get: operations['get_current_user'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/password/request-reset': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Initiates a password reset process by sending an email.
		 * @description # Errors
		 *     Returns an error if the email is invalid or the request fails.
		 */
		post: operations['request_password_reset'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/password/reset': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resets a user's password using a valid reset token.
		 * @description # Errors
		 *     Returns an error if the token is invalid/expired or the operation fails.
		 */
		post: operations['reset_password'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/profile': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Updates the profile information of the currently authenticated user.
		 * @description # Errors
		 *     Returns an error if validation fails or the update operation fails.
		 */
		put: operations['update_profile'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Registers a new company and its administrative user.
		 * @description # Errors
		 *     Returns an error if validation fails, the email already exists, or registration fails.
		 */
		post: operations['register_company_admin'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Verifies the validity of a JWT token.
		 * @description # Errors
		 *     Returns an error if the token is invalid, expired, or if there's a database error.
		 */
		post: operations['verify_token'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/clock/company': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Gets all clock in/out events for the admin's company.
		 * @description # Errors
		 *     Returns an error if the user is not an admin or if DB operations fail.
		 */
		get: operations['get_company_clock_events'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/clock/in': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Clocks in the current user.
		 * @description # Errors
		 *     Returns an error if the user is already clocked in or if DB operations fail.
		 */
		post: operations['clock_in'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/clock/out': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Clocks out the current user.
		 * @description # Errors
		 *     Returns an error if the user is not clocked in or if DB operations fail.
		 */
		post: operations['clock_out'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/clock/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Gets the current clock status and last 5 events for the user.
		 * @description # Errors
		 *     Returns an error if DB operations fail.
		 */
		get: operations['get_clock_status'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/database': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_db_health'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/index-usage': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_db_index_usage'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/slow-queries': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_db_slow_queries'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/table-sizes': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_db_table_sizes'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/llm/generate-layout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generates a log layout using LLM based on user prompt.
		 * @description # Errors
		 *     Returns an error if the user prompt is empty or if LLM generation fails.
		 */
		post: operations['generate_layout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/admin/entries': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Lists all log entries for the company or branch (managers only). */
		get: operations['list_company_log_entries'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/entries': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Lists all log entries for the current user, optionally filtered by template or status.
		 * @description # Errors
		 *     Returns an error if the user is not authorized or if the query fails.
		 */
		get: operations['list_user_log_entries'];
		put?: never;
		/**
		 * Creates a new log entry draft.
		 * @description # Errors
		 *     Returns an error if the template name is empty or if entry creation fails.
		 */
		post: operations['create_log_entry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/entries/due': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Lists all log forms that are due today for the current user's company.
		 * @description # Errors
		 *     Returns an error if the user is not authorized or if the query fails.
		 */
		get: operations['list_due_forms_today'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/entries/{entry_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Retrieves a specific log entry by its ID.
		 * @description # Errors
		 *     Returns an error if the entry is not found or if the user is not authorized.
		 */
		get: operations['get_log_entry'];
		/**
		 * Updates the data of an existing log entry draft.
		 * @description # Errors
		 *     Returns an error if the entry is not found or if the update fails.
		 */
		put: operations['update_log_entry'];
		post?: never;
		/**
		 * Deletes a log entry.
		 * @description # Errors
		 *     Returns an error if the user is not authorized or if deletion fails.
		 */
		delete: operations['delete_log_entry'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/entries/{entry_id}/submit': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Submits a log entry, marking it as final.
		 * @description # Errors
		 *     Returns an error if the entry is not found or if submission fails.
		 */
		post: operations['submit_log_entry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/entries/{entry_id}/unsubmit': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Returns a submitted log entry to draft status (admin only).
		 * @description # Errors
		 *     Returns an error if the entry is not found or if the operation fails.
		 */
		post: operations['unsubmit_log_entry'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Retrieves a specific log template by name. */
		get: operations['get_template'];
		put?: never;
		/** Adds a new log template for the current company. */
		post: operations['add_template'];
		/** Deletes a specific log template. */
		delete: operations['delete_template'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates/all': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Retrieves all log templates for the current company/branch. */
		get: operations['get_all_templates'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates/rename': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Renames an existing log template. */
		put: operations['rename_template'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates/update': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Updates an existing log template. */
		put: operations['update_template'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates/versions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Retrieves the version history of a log template. */
		get: operations['get_template_versions'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates/versions/restore': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Restores a specific version of a log template. */
		post: operations['restore_template_version'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AcceptInvitationRequest: {
			/** @example Alice */
			first_name: string;
			/** @example Smith */
			last_name: string;
			/** @example MemberPass123! */
			password: string;
			/** @example invitation-token-here */
			token: string;
		};
		AddTemplateRequest: {
			/** @example branch-uuid-here */
			branch_id?: string | null;
			schedule: components['schemas']['Schedule'];
			template_layout: components['schemas']['Vec'];
			/** @example Kitchen Daily Log */
			template_name: string;
		};
		AddTemplateResponse: {
			message: string;
		};
		AddTokenResponse: {
			message: string;
		};
		AdminUpdateMemberRequest: {
			/** @example branch-uuid-here */
			branch_id?: string | null;
			/** @example user@example.com */
			email: string;
			/** @example Jane */
			first_name: string;
			/** @example Smith */
			last_name: string;
			/** @example staff */
			role: string;
		};
		AuthResponse: {
			token: string;
			user: components['schemas']['UserResponse'];
		};
		BranchDto: {
			address: string;
			company_id: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			deletion_requested_at?: string | null;
			has_pending_deletion?: boolean;
			id: string;
			name: string;
		};
		CancelInvitationRequest: {
			/** @example invitation-uuid-here */
			invitation_id: string;
		};
		ClockEventResponse: {
			/** Format: date-time */
			clock_in: string;
			/** Format: date-time */
			clock_out?: string | null;
			/** Format: date-time */
			created_at: string;
			id: string;
			status: string;
			user_id: string;
		};
		ClockStatusResponse: {
			current_event?: null | components['schemas']['ClockEventResponse'];
			is_clocked_in: boolean;
			recent_events: components['schemas']['ClockEventResponse'][];
		};
		CompanyClockEventResponse: {
			/** Format: date-time */
			clock_in: string;
			/** Format: date-time */
			clock_out?: string | null;
			/** Format: date-time */
			created_at: string;
			email: string;
			first_name: string;
			id: string;
			last_name: string;
			status: string;
			user_id: string;
		};
		CompanyClockEventsResponse: {
			events: components['schemas']['CompanyClockEventResponse'][];
		};
		ConfirmBranchDeletionRequest: {
			/** @example deletion-token-here */
			token: string;
		};
		ConfirmBranchDeletionResponse: {
			message: string;
		};
		CreateBranchRequest: {
			/** @example 123 Regent St, London */
			address: string;
			/** @example London Office */
			name: string;
		};
		CreateLogEntryRequest: {
			/** @example Kitchen Daily Log */
			template_name: string;
		};
		CreateLogEntryResponse: {
			id: string;
			message: string;
		};
		DatabaseHealthMetrics: {
			/** Format: int64 */
			active_connections: number;
			/** Format: double */
			database_size_mb: number;
			/** Format: int64 */
			idle_connections: number;
			/** Format: int64 */
			index_count: number;
			/** Format: int32 */
			max_connections: number;
			/** Format: int64 */
			table_count: number;
			/** Format: int64 */
			total_connections: number;
		};
		DeleteTemplateRequest: {
			template_name: string;
		};
		DeleteTemplateResponse: {
			message: string;
		};
		DueFormInfo: {
			last_submitted?: string | null;
			period: string;
			status?: string | null;
			template_layout: components['schemas']['Vec'];
			template_name: string;
		};
		DueFormsResponse: {
			forms: components['schemas']['DueFormInfo'][];
		};
		ErrorResponse: {
			error: string;
		};
		/** @enum {string} */
		Frequency: 'Daily' | 'Weekly' | 'Monthly' | 'Yearly';
		GetAllTemplatesResponse: {
			templates: components['schemas']['TemplateInfo'][];
		};
		GetCompanyMembersResponse: {
			members: components['schemas']['UserResponse'][];
		};
		GetInvitationDetailsRequest: {
			/** @example invitation-token-here */
			token: string;
		};
		GetInvitationDetailsResponse: {
			company_name: string;
			/** Format: date-time */
			expires_at: string;
		};
		GetPendingInvitationsResponse: {
			invitations: components['schemas']['InvitationResponse'][];
		};
		GetTemplateRequest: {
			/** @example Kitchen Daily Log */
			template_name: string;
		};
		GetTemplateResponse: {
			template_layout: components['schemas']['Vec'];
			template_name: string;
			/** Format: int32 */
			version: number;
			version_name?: string | null;
		};
		GetTemplateVersionsResponse: {
			versions: components['schemas']['TemplateVersionInfo'][];
		};
		HealthResponse: {
			metrics: components['schemas']['DatabaseHealthMetrics'];
			status: string;
		};
		IndexUsageResponse: {
			indexes: components['schemas']['IndexUsageStats'][];
			unused_indexes: string[];
		};
		IndexUsageStats: {
			index_name: string;
			/** Format: int64 */
			index_scans: number;
			/** Format: int64 */
			rows_fetched: number;
			/** Format: int64 */
			rows_read: number;
			table_name: string;
		};
		InvitationResponse: {
			email: string;
			/** Format: date-time */
			expires_at: string;
			id: string;
		};
		InviteUserRequest: {
			/** @example branch-uuid-here */
			branch_id?: string | null;
			/** @example newmember@example.com */
			email: string;
			role?: null | components['schemas']['UserRole'];
		};
		JwtVerifyResponse: {
			email: string;
		};
		LayoutGenerationRequest: {
			user_prompt: string;
		};
		LayoutGenerationResponse: {
			layout: unknown;
		};
		ListBranchesResponse: {
			branches: components['schemas']['BranchDto'][];
		};
		ListLogEntriesResponse: {
			entries: components['schemas']['LogEntryResponse'][];
		};
		LogEntryResponse: {
			created_at: string;
			entry_data: unknown;
			id: string;
			period: string;
			status: string;
			submitted_at?: string | null;
			template_layout: components['schemas']['Vec'];
			template_name: string;
			updated_at: string;
		};
		LoginRequest: {
			/** @example admin@example.com */
			email: string;
			/** @example SecurePass123! */
			password: string;
		};
		OAuthCallbackRequest: {
			/** @example authorization-code-from-google */
			code: string;
			/** @example csrf-state-token */
			state: string;
		};
		OAuthInitiateResponse: {
			authorization_url: string;
		};
		OAuthLinkConfirmRequest: {
			link_token: string;
		};
		PasswordResetResponse: {
			message: string;
		};
		Position: {
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		RegisterRequest: {
			/** @example 123 Main St, City, Country */
			company_address: string;
			/** @example Example Corp */
			company_name: string;
			/** @example admin@example.com */
			email: string;
			/** @example John */
			first_name: string;
			/** @example Doe */
			last_name: string;
			/** @example SecurePass123! */
			password: string;
		};
		RemoveMemberRequest: {
			/** @example user@example.com */
			email: string;
		};
		RenameTemplateRequest: {
			new_template_name: string;
			old_template_name: string;
		};
		RenameTemplateResponse: {
			message: string;
		};
		RequestBranchDeletionRequest: {
			/** @example 550e8400-e29b-41d4-a716-446655440000 */
			branch_id: string;
		};
		RequestBranchDeletionResponse: {
			message: string;
		};
		RequestPasswordResetRequest: {
			/** @example user@example.com */
			email: string;
		};
		ResetPasswordRequest: {
			/** @example NewPassword123! */
			new_password: string;
			/** @example reset-token-here */
			token: string;
		};
		RestoreTemplateVersionRequest: {
			/** Format: int32 */
			version: number;
		};
		Schedule: {
			/** Format: int32 */
			day_of_month?: number | null;
			/** Format: int32 */
			day_of_week?: number | null;
			days_of_week?: number[] | null;
			frequency: components['schemas']['Frequency'];
			/** Format: int32 */
			month_of_year?: number | null;
		};
		SlowQueriesResponse: {
			queries: components['schemas']['SlowQueryInfo'][];
		};
		SlowQueryInfo: {
			/** Format: int64 */
			calls: number;
			/** Format: double */
			max_time_ms: number;
			/** Format: double */
			mean_time_ms: number;
			query: string;
			/** Format: double */
			total_time_ms: number;
		};
		SubmitLogEntryRequest: Record<string, never>;
		SubmitLogEntryResponse: {
			message: string;
		};
		TableSizeInfo: {
			/** Format: double */
			index_size_mb: number;
			/** Format: int64 */
			row_count: number;
			table_name: string;
			/** Format: double */
			table_size_mb: number;
			/** Format: double */
			total_size_mb: number;
		};
		TableSizesResponse: {
			tables: components['schemas']['TableSizeInfo'][];
		};
		TemplateDocument: {
			branch_id?: string | null;
			company_id: string;
			/** Format: date-time */
			created_at: string;
			/** Format: uuid */
			created_by: string;
			schedule: components['schemas']['Schedule'];
			template_layout: components['schemas']['Vec'];
			template_name: string;
			/** Format: date-time */
			updated_at: string;
			/** Format: int32 */
			version?: number;
			version_name?: string | null;
		};
		TemplateField: {
			field_type: string;
			position: components['schemas']['Position'];
			props: components['schemas']['TemplateFieldProps'];
		};
		TemplateFieldProps: {
			editable?: boolean | null;
			/** Format: float */
			max?: number | null;
			/** Format: float */
			min?: number | null;
			options?: string[] | null;
			placeholder?: string | null;
			selected?: string | null;
			size?: string | null;
			text?: string | null;
			unit?: string | null;
			value?: string | null;
			weight?: string | null;
		};
		TemplateInfo: {
			created_at: string;
			created_by: string;
			schedule: components['schemas']['Schedule'];
			template_name: string;
			updated_at: string;
		};
		TemplateVersionInfo: {
			created_at: string;
			created_by: string;
			/** Format: int32 */
			version: number;
			version_name?: string | null;
		};
		UpdateBranchRequest: {
			/** @example 123 Regent St, London */
			address: string;
			/** @example 550e8400-e29b-41d4-a716-446655440000 */
			branch_id: string;
			/** @example London Office */
			name: string;
		};
		UpdateLogEntryRequest: {
			entry_data: unknown;
		};
		UpdateProfileRequest: {
			/** @example John */
			first_name: string;
			/** @example Doe */
			last_name: string;
		};
		UpdateTemplateRequest: {
			schedule?: null | components['schemas']['Schedule'];
			template_layout?: null | components['schemas']['Vec'];
			/** @example Kitchen Daily Log */
			template_name: string;
			/** @example Major Update */
			version_name?: string | null;
		};
		UpdateTemplateResponse: {
			message: string;
		};
		UserResponse: {
			branch_id?: string | null;
			company_id?: string | null;
			company_name?: string | null;
			/** Format: date-time */
			created_at: string;
			email: string;
			first_name: string;
			id: string;
			last_name: string;
			oauth_provider?: string | null;
			role: components['schemas']['UserRole'];
		};
		/** @enum {string} */
		UserRole: 'logsmart_admin' | 'company_manager' | 'branch_manager' | 'staff';
		Vec: {
			field_type: string;
			position: components['schemas']['Position'];
			props: components['schemas']['TemplateFieldProps'];
		}[];
		VerifyTokenRequest: {
			/** @example jwt-token-here */
			token: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	admin_delete_member: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RemoveMemberRequest'];
			};
		};
		responses: {
			/** @description Member deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - not an admin or different company */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	admin_update_member_profile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AdminUpdateMemberRequest'];
			};
		};
		responses: {
			/** @description Member profile updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetCompanyMembersResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - not an admin or different company */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	list_branches: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Branches retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ListBranchesResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_branch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateBranchRequest'];
			};
		};
		responses: {
			/** @description Branch updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BranchDto'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - only company manager can update branches */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Branch not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	create_branch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateBranchRequest'];
			};
		};
		responses: {
			/** @description Branch created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BranchDto'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - only company manager can create branches */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_company_members: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Company members retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetCompanyMembersResponse'][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	google_callback: {
		parameters: {
			query: {
				/** @description Authorization code from Google */
				code: string;
				/** @description CSRF state token */
				state: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirect to dashboard on success or login on error */
			302: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Authentication failed */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	initiate_google_login: {
		parameters: {
			query?: {
				/** @description OAuth mode: 'link' or omit for login */
				mode?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OAuth flow initiated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OAuthInitiateResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	link_google_account: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['OAuthCallbackRequest'];
			};
		};
		responses: {
			/** @description Google account linked successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Account already linked */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	confirm_google_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['OAuthLinkConfirmRequest'];
			};
		};
		responses: {
			/** @description Google account linked successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Account already linked */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	unlink_google_account: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Google account unlinked successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Cannot unlink - password required */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	accept_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AcceptInvitationRequest'];
			};
		};
		responses: {
			/** @description Invitation accepted successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired invitation token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	cancel_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CancelInvitationRequest'];
			};
		};
		responses: {
			/** @description Invitation cancelled successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request or invitation already accepted/cancelled */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - not an admin or different company */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invitation not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_invitation_details: {
		parameters: {
			query: {
				token: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Invitation details retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetInvitationDetailsResponse'];
				};
			};
			/** @description Invitation not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_pending_invitations: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Invitations retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationResponse'][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	invite_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['InviteUserRequest'];
			};
		};
		responses: {
			/** @description Invitation sent successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User already invited or exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LoginRequest'];
			};
		};
		responses: {
			/** @description Login successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid credentials */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_current_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current user information */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	request_password_reset: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RequestPasswordResetRequest'];
			};
		};
		responses: {
			/** @description Password reset email sent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PasswordResetResponse'];
				};
			};
			/** @description Invalid email */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	reset_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ResetPasswordRequest'];
			};
		};
		responses: {
			/** @description Password reset successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PasswordResetResponse'];
				};
			};
			/** @description Password validation failed */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_profile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateProfileRequest'];
			};
		};
		responses: {
			/** @description Profile updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	register_company_admin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RegisterRequest'];
			};
		};
		responses: {
			/** @description Company admin registered successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Email already exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	verify_token: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VerifyTokenRequest'];
			};
		};
		responses: {
			/** @description Token is valid */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JwtVerifyResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_company_clock_events: {
		parameters: {
			query?: {
				/** @description ISO 8601 start date filter (inclusive) */
				from?: string | null;
				/** @description ISO 8601 end date filter (inclusive) */
				to?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description All company clock events */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyClockEventsResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden – admin only */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	clock_in: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successfully clocked in */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ClockEventResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Already clocked in */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	clock_out: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successfully clocked out */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ClockEventResponse'];
				};
			};
			/** @description Not currently clocked in */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_clock_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current clock status and recent events */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ClockStatusResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_db_health: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Database health metrics retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden - LogSmart admin only */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_db_index_usage: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Index usage statistics retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IndexUsageResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden - LogSmart admin only */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_db_slow_queries: {
		parameters: {
			query?: {
				/** @description Maximum number of slow queries to return (default: 20) */
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Slow queries retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SlowQueriesResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden - LogSmart admin only */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_db_table_sizes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Table sizes retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TableSizesResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden - LogSmart admin only */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	generate_layout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LayoutGenerationRequest'];
			};
		};
		responses: {
			/** @description Layout generated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_company_log_entries: {
		parameters: {
			query: {
				/** @description Optional comma-separated list of branch IDs to filter by (managers only) */
				branch_ids: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Company log entries retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ListLogEntriesResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - only managers can view all entries */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	list_user_log_entries: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User log entries retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ListLogEntriesResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	create_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateLogEntryRequest'];
			};
		};
		responses: {
			/** @description Log entry created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CreateLogEntryResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Template not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	list_due_forms_today: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Due forms retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DueFormsResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Log entry retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LogEntryResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - entry does not belong to user */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Entry not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateLogEntryRequest'];
			};
		};
		responses: {
			/** @description Log entry updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LogEntryResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - entry does not belong to user */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Entry not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	delete_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Log entry deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - entry does not belong to user */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Entry not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	submit_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Log entry submitted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SubmitLogEntryResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - entry does not belong to user */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Entry not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	unsubmit_log_entry: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				entry_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Log entry returned to draft successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SubmitLogEntryResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden - only admins can unsubmit entries */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Entry not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_template: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/**
				 * @description Name of the template to retrieve
				 * @example ErrorLog
				 */
				template_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Template retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetTemplateResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Template not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	add_template: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddTemplateRequest'];
			};
		};
		responses: {
			/** @description Template added successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AddTemplateResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	delete_template: {
		parameters: {
			query: {
				template_name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Template deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeleteTemplateResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_all_templates: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description All templates retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetAllTemplatesResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	rename_template: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RenameTemplateRequest'];
			};
		};
		responses: {
			/** @description Template renamed successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RenameTemplateResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_template: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateTemplateRequest'];
			};
		};
		responses: {
			/** @description Template updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UpdateTemplateResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_template_versions: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/**
				 * @description Name of the template to retrieve versions for
				 * @example ErrorLog
				 */
				template_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Versions retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetTemplateVersionsResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	restore_template_version: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/**
				 * @description Name of the template to restore
				 * @example ErrorLog
				 */
				template_name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RestoreTemplateVersionRequest'];
			};
		};
		responses: {
			/** @description Template restored successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UpdateTemplateResponse'];
				};
			};
			/** @description Bad request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
}
