/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/auth/company/members': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_company_members'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/accept': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['accept_invitation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/details': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_invitation_details'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invitations/send': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['invite_user'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['login'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_current_user'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/password/request-reset': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['request_password_reset'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/password/reset': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['reset_password'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/profile': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations['update_profile'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['register_company_admin'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['verify_token'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/logs/templates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_template'];
		put?: never;
		post: operations['add_template'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AcceptInvitationRequest: {
			/** @example Alice */
			first_name: string;
			/** @example Smith */
			last_name: string;
			/** @example MemberPass123! */
			password: string;
			/** @example invitation-token-here */
			token: string;
		};
		AddTemplateRequest: {
			template_layout: components['schemas']['Vec'];
			/** @example Kitchen Daily Log */
			template_name: string;
		};
		AddTemplateResponse: {
			message: string;
		};
		AddTokenResponse: {
			message: string;
		};
		AuthResponse: {
			token: string;
			user: components['schemas']['UserResponse'];
		};
		ErrorResponse: {
			error: string;
		};
		GetCompanyMembersResponse: {
			members: components['schemas']['UserResponse'][];
		};
		GetInvitationDetailsRequest: {
			/** @example invitation-token-here */
			token: string;
		};
		GetInvitationDetailsResponse: {
			company_name: string;
			expires_at: string;
		};
		GetTemplateRequest: {
			/** @example Kitchen Daily Log */
			template_name: string;
		};
		GetTemplateResponse: {
			template_layout: components['schemas']['Vec'];
			template_name: string;
		};
		InvitationResponse: {
			email: string;
			expires_at: string;
			id: string;
		};
		InviteUserRequest: {
			/** @example newmember@example.com */
			email: string;
		};
		JwtVerifyResponse: {
			email: string;
		};
		LoginRequest: {
			/** @example admin@example.com */
			email: string;
			/** @example SecurePass123! */
			password: string;
		};
		PasswordResetResponse: {
			message: string;
		};
		Position: {
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
		};
		RegisterRequest: {
			/** @example 123 Main St, City, Country */
			company_address: string;
			/** @example Example Corp */
			company_name: string;
			/** @example admin@example.com */
			email: string;
			/** @example John */
			first_name: string;
			/** @example Doe */
			last_name: string;
			/** @example SecurePass123! */
			password: string;
		};
		RequestPasswordResetRequest: {
			/** @example user@example.com */
			email: string;
		};
		ResetPasswordRequest: {
			/** @example NewPassword123! */
			new_password: string;
			/** @example reset-token-here */
			token: string;
		};
		TemplateDocument: {
			company_id: string;
			template_layout: components['schemas']['Vec'];
			template_name: string;
		};
		TemplateField: {
			field_type: string;
			label?: string | null;
			name: string;
			placeholder?: string | null;
			position: components['schemas']['Position'];
			required: boolean;
		};
		UpdateProfileRequest: {
			/** @example John */
			first_name: string;
			/** @example Doe */
			last_name: string;
		};
		UserResponse: {
			company_name?: string | null;
			email: string;
			first_name: string;
			last_name: string;
			role: string;
		};
		Vec: {
			field_type: string;
			label?: string | null;
			name: string;
			placeholder?: string | null;
			position: components['schemas']['Position'];
			required: boolean;
		}[];
		VerifyTokenRequest: {
			/** @example jwt-token-here */
			token: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_company_members: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Company members retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetCompanyMembersResponse'][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	accept_invitation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AcceptInvitationRequest'];
			};
		};
		responses: {
			/** @description Invitation accepted successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired invitation token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_invitation_details: {
		parameters: {
			query: {
				token: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Invitation details retrieved successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetInvitationDetailsResponse'];
				};
			};
			/** @description Invitation not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	invite_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['InviteUserRequest'];
			};
		};
		responses: {
			/** @description Invitation sent successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InvitationResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User already invited or exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LoginRequest'];
			};
		};
		responses: {
			/** @description Login successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid credentials */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_current_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current user information */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserResponse'];
				};
			};
			/** @description Unauthorized - invalid or missing token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	request_password_reset: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RequestPasswordResetRequest'];
			};
		};
		responses: {
			/** @description Password reset email sent */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PasswordResetResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	reset_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ResetPasswordRequest'];
			};
		};
		responses: {
			/** @description Password reset successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PasswordResetResponse'];
				};
			};
			/** @description Password validation failed */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	update_profile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateProfileRequest'];
			};
		};
		responses: {
			/** @description Profile updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	register_company_admin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RegisterRequest'];
			};
		};
		responses: {
			/** @description Company admin registered successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request data */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Email already exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Rate limit exceeded */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	verify_token: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VerifyTokenRequest'];
			};
		};
		responses: {
			/** @description Token is valid */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JwtVerifyResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	get_template: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/**
				 * @description Name of the template to retrieve
				 * @example ErrorLog
				 */
				template_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Password reset successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetTemplateResponse'];
				};
			};
			/** @description Password validation failed */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	add_template: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddTemplateRequest'];
			};
		};
		responses: {
			/** @description Template added successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AddTemplateResponse'];
				};
			};
			/** @description Password validation failed */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid or expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
}
