use crate::{dto, handlers, logs_db};
use utoipa::OpenApi;

#[allow(clippy::needless_for_each)]
#[derive(OpenApi)]
#[openapi(
    paths(
        handlers::register_company_admin,
        handlers::login,
        handlers::verify_token,
        handlers::get_current_user,
        handlers::invite_user,
        handlers::accept_invitation,
        handlers::cancel_invitation,
        handlers::update_profile,
        handlers::request_password_reset,
        handlers::reset_password,
        handlers::add_template,
        handlers::get_template,
        handlers::get_company_members,
        handlers::admin_update_member_profile,
        handlers::admin_delete_member,
        handlers::get_invitation_details,
        handlers::get_all_templates,
        handlers::update_template,
        handlers::rename_template,
        handlers::delete_template,
        handlers::list_due_forms_today,
        handlers::create_log_entry,
        handlers::get_log_entry,
        handlers::update_log_entry,
        handlers::submit_log_entry,
        handlers::unsubmit_log_entry,
        handlers::delete_log_entry,
        handlers::list_user_log_entries,
        handlers::generate_layout,
        handlers::get_db_health,
        handlers::get_db_slow_queries,
        handlers::get_db_index_usage,
        handlers::get_db_table_sizes,
        handlers::get_pending_invitations,
        handlers::initiate_google_login,
        handlers::google_callback,
        handlers::link_google_account,
        handlers::confirm_google_link,
        handlers::unlink_google_account,
    ),
    components(
        schemas(
            dto::RegisterRequest,
            dto::LoginRequest,
            dto::AuthResponse,
            dto::InviteUserRequest,
            dto::AcceptInvitationRequest,
            dto::CancelInvitationRequest,
            dto::VerifyTokenRequest,
            dto::UserResponse,
            dto::InvitationResponse,
            dto::ErrorResponse,
            dto::JwtVerifyResponse,
            dto::UpdateProfileRequest,
            dto::RequestPasswordResetRequest,
            dto::ResetPasswordRequest,
            dto::PasswordResetResponse,
            dto::AddTemplateRequest,
            dto::GetTemplateRequest,
            dto::GetTemplateResponse,
            dto::AddTemplateResponse,
            dto::AddTokenResponse,
            dto::AdminUpdateMemberRequest,
            dto::RemoveMemberRequest,
            dto::GetCompanyMembersResponse,
            dto::GetInvitationDetailsRequest,
            dto::GetInvitationDetailsResponse,
            dto::GetPendingInvitationsResponse,
            dto::GetAllTemplatesResponse,
            dto::TemplateInfo,
            dto::UpdateTemplateRequest,
            dto::UpdateTemplateResponse,
            dto::RenameTemplateRequest,
            dto::RenameTemplateResponse,
            dto::DeleteTemplateRequest,
            dto::DeleteTemplateResponse,
            dto::CreateLogEntryRequest,
            dto::CreateLogEntryResponse,
            dto::LogEntryResponse,
            dto::UpdateLogEntryRequest,
            dto::SubmitLogEntryRequest,
            dto::SubmitLogEntryResponse,
            dto::DueFormInfo,
            dto::DueFormsResponse,
            dto::ListLogEntriesResponse,
            dto::LayoutGenerationRequest,
            dto::LayoutGenerationResponse,
            handlers::HealthResponse,
            handlers::SlowQueriesResponse,
            handlers::IndexUsageResponse,
            handlers::TableSizesResponse,
            crate::db::DatabaseHealthMetrics,
            crate::db::SlowQueryInfo,
            crate::db::IndexUsageStats,
            crate::db::TableSizeInfo,
            logs_db::TemplateDocument,
            logs_db::TemplateField,
            logs_db::Position,
            logs_db::Schedule,
            logs_db::Frequency,
            logs_db::TemplateLayout,
            logs_db::TemplateFieldProps,
            dto::OAuthCallbackRequest,
            dto::OAuthInitiateResponse,
            handlers::OAuthLinkConfirmRequest,
        )
    ),
    tags(
        (name = "Authentication", description = "User authentication and registration endpoints"),
        (name = "Invitations", description = "Company member invitation management"),
        (name = "Templates", description = "Template management"),
        (name = "Company Management", description = "Company member management"),
        (name = "Log Entries", description = "Log entry management"),
        (name = "Health Monitoring", description = "Database health and performance monitoring (LogSmart Admin only)"),
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

pub struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::Http::new(
                        utoipa::openapi::security::HttpAuthScheme::Bearer,
                    ),
                ),
            );
        }
    }
}
